## 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np 
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2. Create a vector with values ranging from 10 to 49.

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
x=np.array([1,2,0,0,4,0])
print("indices of non-zero elements are:",np.nonzero(x))

indices of non-zero elements are: (array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
import random
random.seed(10)
x=np.random.random(size=(10,10))
print("Minimum vales:",x.min())
print("Maximum values:",x.max())
print(x)

Minimum vales: 0.003485807693781706
Maximum values: 0.9801094004373603
[[0.86523963 0.92754903 0.01210272 0.34850511 0.20647813 0.55639474
  0.15804383 0.94965957 0.18081817 0.26951492]
 [0.75156401 0.29921268 0.6600651  0.34154997 0.16990402 0.75474259
  0.06968132 0.41347326 0.91258346 0.18812661]
 [0.13377934 0.28137455 0.32786113 0.29934626 0.69974757 0.95495226
  0.57293275 0.35899896 0.62667152 0.91486637]
 [0.04756793 0.51727005 0.36003569 0.66067079 0.64477281 0.81659234
  0.34736849 0.45102898 0.49366874 0.18672966]
 [0.23638161 0.83427943 0.01188009 0.5360297  0.01830171 0.78240345
  0.33306108 0.77702167 0.5791599  0.64428632]
 [0.7333447  0.82516782 0.9077152  0.25990532 0.91625832 0.00348581
  0.00735961 0.29239424 0.72492762 0.59617783]
 [0.57468362 0.27705271 0.85621733 0.0599964  0.489359   0.00936016
  0.14032846 0.20768561 0.87068709 0.58233499]
 [0.12965212 0.89504445 0.47153737 0.9266039  0.02414743 0.66227099
  0.5325572  0.34255996 0.03032504 0.88982862]
 [0.66237

## 6. Create a random vector of size 30 and find the mean value.

In [8]:
arr=np.random.random((5,6))
Mean_value_of_the_matrix=np.mean(arr)
print("mean:",Mean_value_of_the_matrix)

mean: 0.43516255592712033
